FROM dustynv/ros:jazzy-ros-base-r36.4.0-cu128-24.04


ARG USERNAME=RoboSub
ARG USER_UID=1001
ARG USER_GID=$USER_UID

RUN apt-key del F42ED6FBAB17C654 || true
RUN curl -fsSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg

RUN apt-get update && apt-get install -y curl gnupg2 lsb-release

# Add ROS 2 repo using the keyring
RUN echo "source /opt/ros/jazzy/setup.bash" >> ~/.bashrc \
    && echo "source /workspaces/RoboSub_AUV/install/setup.bash" >> ~/.bashrc

RUN echo "deb [signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" \
    > /etc/apt/sources.list.d/ros2.list
    
RUN apt update
#RUN curl -fsSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
# Create user and install packages
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && apt-get install -y \
        sudo \
        dos2unix \
        python3-colcon-common-extensions \
        python3-rosdep \
        git \
        build-essential \
        ros-jazzy-pcl-conversions \
        ros-jazzy-pcl-ros \
	libglm-dev \
    	libsdl2-dev \
    	libfreetype6-dev \
    	libglew-dev \
    pkg-config \
    && rm -rf /var/lib/apt/lists/* \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

USER $USERNAME

RUN sudo rosdep init || true
RUN rosdep update

WORKDIR /workspaces/RoboSub_AUV
COPY ros2_ws ./ros2_ws

RUN sudo apt-get update && /bin/bash -c "source /opt/ros/jazzy/setup.bash && \
    rosdep install --from-paths ros2_ws/src --ignore-src -r -y"

RUN /bin/bash -c "source /opt/ros/jazzy/setup.bash && colcon build --symlink-install"

RUN find /workspaces/RoboSub_AUV/ros2_ws/src -name "*.py" -exec sudo chmod +x {} \;
